{{- if .Values.exporters.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exporters
spec:
  destination:
    name: {{ .Values.destination.cluster }}
    namespace: {{ .Values.exporters.namespace }}
  source:
    path: exporter-bootstrap
    repoURL: 'https://github.com/KevinCHiggins/charts'
    targetRevision: multi-postgres
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end }}
