{{- if .Values.prometheuswithexporters.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "prometheus-with-exporters"
spec:
  destination:
    name: {{ .Values.destination.cluster }}
    namespace: {{ .Values.prometheuswithexporters.namespace }}
  source:
    path: {{ .Values.prometheuswithexporters.path }}
    repoURL: {{ .Values.prometheuswithexporters.repourl }}
    targetRevision: {{ .Values.prometheuswithexporters.targetrevision }}
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end }}